---
name: Check links in README.md

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: /github/workspace/README.md --allow-timeout --allow-dupe --request-delay 1 --allow-redirect --white-list https://img.shields.io,https://jira.example.com
